// ./src/models/v1/osuZodEnums.ts
//
// Zod enums containing data about OSU undergraduate year, major, and pre prof.

// Zod essential imports.
import { z } from "zod";

// Undergraduate year enums.
export enum NativeUndergradYears {
  HighSchool =  "High School",
  Freshman =    "Freshman (1st Year)",
  Sophomore =   "Sophomore (2nd Year)",
  Junior =      "Junior (3rd Year)",
  Senior =      "Senior (4th Year)",
  SuperSenior = "SuperSenior (5+ Years)",
}
// Undergraduate year (native) enums as Zod enums.
export const UndergradYears = z.nativeEnum(NativeUndergradYears);
export type UndergradYears = z.infer<typeof UndergradYears>;

// Undergraduate major enums.
// NOTE!
// Data manually collected on 06/28/24
// from `https://undergrad.osu.edu/majors-and-academics/majors`.
export enum NativeUndergradMajors {
  Accounting =                                                  "Accounting",
  ActuarialScience = "Actuarial science",
  AerospaceEngineering = "Aerospace Engineering",
  AfricanAmericanAndAfricanStudies = "African American and African Studies",
  Agribusiness = "Agribusiness",
  AgriculturalAndAppliedEconomics = "Agricultural and Applied Economics",
  ArgiculturalCommunication = "Agricultural Communication",
  AgriculturalSystemsManagement = "Agricultural Systems Management",
  AgricultureExploring = "Agriculture, Exploring",
  AgriscienceEducation = "Agriscience Education",
  Agronomy = "Agronomy",
  AncientHistoryAndClassics = "Ancient History and Classics",
  AnimalSciences = "Animal Sciences",
  AnthropologicalSciences = "Anthropological Sciences",
  Anthropology = "Anthropology",
  Arabic = "Arabic",
  Architecture = "Architecture",
  Art = "Art",
  ArtEducation = "Art Education",
  ArtsAndSciencesUndecided = "Arts and Sciences, Undecided",
  ArtsManagement = "Arts Management",
  AstronomyAndAstrophysics = "Astronomy and Astrophysics",
  AtmosphericSciences = "Atmospheric Sciences",
  Aviation = "Aviation",
  AviationManagement = "Aviation Management",
  BiochemicalSciences = "Biochemical Sciences",
  Biochemistry = "Biochemistry",
  Biology = "Biology",
  BiomedicalEngineering = "Biomedical Engineering",
  BiomedicalScience = "Biomedical Science",
  BusinessAdministrationUndecided = "Business Administration, Undecided",
  BusinessManagement = "Business Management",
  ChemicalEngineering = "Chemical Engineering",
  Chemistry = "Chemistry",
  ChildAndYouthStudies = "Child and Youth Studies",
  Chinese = "Chinese",
  CityAndRegionalPlanning = "City and Regional Planning",
  CivilEngineering = "Civil Engineering",
  Classics = "Classics",
  Communication = "Communication",
  CommunityLeadership = "Community Leadership",
  ComparativeStudies = "Comparative Studies",
  ComputerAndInformationScience = "Computer and Information Science",
  ComputerScienceAndEngineering = "Computer Science and Engineering",
  ConstructionManagement = "Construction Management",
  ConstructionSystemsManagement = "Construction Systems Management",
  ConsumerAndFamilyFinancialServices = "Consumer and Family Financial Services",
  CriminologyAndCriminalJusticeStudies = "Criminology and Criminal Justice Studies",
  CropManagementAndSoilConservation = "Crop Management and Soil Conservation",
  CulinaryScience = "Culinary Science",
  DairyCattleProductionAndManagement = "Dairy Cattle Production and Management",
  Dance = "Dance",
  DataAnalytics = "Data Analytics",
  DentalHygiene = "Dental Hygiene",
  DentalHygieneBaccalaureateCompletionProgram = "Dental Hygiene (Baccaulaureate Completion Program)",
  EarthSciences = "Earth Sciences",
  Economics = "Economics",
  EconomicsBusiness = "Economic - Business",
  EducationIntegratedLanguageArtsEnglishEducation = "Education - Integrated Language Arts/English Education",
  EducationMiddleChildhoodEducation = "Education - Middle Childhood Education",
  EducationPrimaryEducation = "Education - Primary Education",
  EducationScienceAndMathematicsEducation = "Education - Science and Mathematics Education",
  EducationSpecialEducation = "Education - Special Education",
  EducationTeachingEnglishToSpeakersOfOtherLanguages = "Education - Teaching English to Speakers of Other Languages",
  EducationTechnicalEducationAndTraining = "Education - Technical Education and Training",
  EducationWorldLanguageEducation = "Education - World Language Education",
  ElectricalAndComputerEngineering = "Electrical and Computer Engineering",
  EngineeringPhysics = "Engineering Physics",
  EngineeringTechnology = "Engineering Technology",
  English = "English",
  Entomology = "Entomology",
  EnvironmentAndNaturalResources = "Environment and Natural Resources",
  EnvironmentAndNaturalResourcesUndecided = "Environment and Natural Resources, Undecided",
  EnvironmentEconomyDevelopmentAndSustainability = "Environment, Economy, Development, and Sustainability",
  EnvironmentalEngineering = "Environmental Engineering",
  EnvironmentalPolicyAndDecisionMaking = "Environmental Policy and Decision Making",
  EnvironmentalScience = "Environmental Science",
  EvolutionAndEcology = "Evolution and Ecology",
  ExerciseScienceEducation = "Exercise Science Education",
  FashionAndRetailStudies = "Fashion and Retail Studies",
  FilmStudies = "Film Studies",
  Finance = "Finance",
  FoodBusinessManagement = "Food Business Management",
  FoodScienceAndTechnology = "Food Science and Technology",
  FoodAgriculturalAndBiologicalEngineering = "Food, Agricultural, and Biological Engineering",
  ForensicAnthropology = "Forensic Anthropology",
  ForestryFisheriesAndWildlife = "Forestry, Fisheries, and Wildlife",
  French = "French",
  FrenchAndFrancophoneStudies = "French and Francophone Studies",
  GeographicInformationScience = "Geographic Information Science",
  Geography = "Geography",
  German = "German",
  GreenhouseAndNurseryManagement =                                  "Greenhouse and Nursery Management",
  HealthAndRehabilitationSciencesUndecided =                        "Health and Rehabilitation Sciences, Undecided",
  HealthAndWellness =                                               "Health and Wellness",
  HealthInformationManagementAndSystems =                           "Health Information Management and Systems",
  HealthPromotionNutritionAndExerciseScience =                      "Health Promotion, Nutrition, and Exercise Science",
  HealthSciences =                                                  "Health Sciences",
  HebrewAndJewishStudies =                                          "Hebrew and Jewish Studies",
  History =                                                         "History",
  HistoryOfArt =                                                    "History of Art",
  HorseProductionAndManagement =                                    "Horse Production and Management",
  HorticultureScience =                                             "Horticulture Science",
  HospitalityManagement =                                           "Hospitality Management",
  HumanDevelopmentAndFamilyScience =                                "Human Development and Family Science",
  HumanNutrition =                                                  "Human Nutrition",
  HumanResources =                                                  "Human Resources",
  HydraulicPowerAndMotionControl =                                  "Hydraulic Power and Motion Control",
  HydraulicServiceAndRepair =                                       "Hydraulic Service and Repair",
  IndustrialAndSystemsEngineering =                                 "Industrial and Systems Engineering",
  IndustrialDesign =                                                "Industrial Design",
  InformationSystems =                                              "Information Systems",
  Insurance =                                                       "Insurance",
  IntegratedMajorInMathematicsAndEnglish =                          "Integrated Major in Mathematics and English",
  InteriorDesign =                                                  "Interior Design",
  InternationalBusiness =                                           "International Business",
  InternationalStudies =                                            "International Studies",
  IslamicStudies =                                                  "Islamic Studies",
  Italian =                                                         "Italian",
  ItalianStudies =                                                  "Italian Studies",
  Japanese =                                                        "Japanese",
  Journalism =                                                      "Journalism",
  Korean =                                                          "Korean",
  LandscapeArchitecture =                                           "Landscape Architecture",
  LandscapeHorticulture =                                           "Landscape Horticulture",
  Linguisitics =                                                    "Linguistics",
  LivestockProductionAndManagement =                                "Livestock Production and Management",
  LogisticsManagement =                                             "Logistics Management",
  Marketing =                                                       "Marketing",
  MaterialsScienceAndEngineering =                                  "Materials Science and Engineering",
  Mathematics =                                                     "Mathematics",
  MechanicalEngineering =                                           "Mechanical Engineering",
  MedicalAnthropology =                                             "Medical Anthropology",
  MedicalLaboratoryScience =                                        "Medical Laboratory Science",
  MedievalAndRenaissanceStudies =                                   "Medieval and Renaissance Studies",
  Microbiology =                                                    "Microbiology",
  ModernGreek =                                                     "Modern Greek",
  MolecularGenetics =                                               "Molecular Genetics",
  MovingImageProduction =                                           "Moving-Image Production",
  Music =                                                           "Music",
  MusicComposition =                                                "Music - Composition",
  MusicEducation =                                                  "Music - Education",
  MusicJazzStudies =                                                "Music - Jazz Studies",
  MusicMusicology =                                                 "Music - Musicology",
  MusicPerformanceOrchestralInstruments =                           "Music - Performance (Orchestral Instruments)",
  MusicPerformancePiano =                                           "Music - Performance (Piano)",
  MusicPerformanceVoice =                                           "Music - Performance (Voice)",
  MusicTheory =                                                     "Music - Theory",
  NaturalResourcesManagement =                                      "Natural Resources Management",
  Neuroscience =                                                    "Neuroscience",
  Nursing =                                                         "Nursing",
  NursingRNToBSN =                                                  "Nursing (RN to BSN)",
  OccupationalTherapy =                                             "Occupational Therapy",
  OperationsManagement =                                            "Operations Management",
  PharmaceuticalSciences =                                          "Pharmaceutical Sciences",
  Philosophy =                                                      "Philosophy",
  PhilosophyPoliticsAndEconomics =                                  "Philosophy, Politics, and Economics",
  PhysicalTherapy =                                                 "Physical Therapy",
  Physics =                                                         "Physics",
  PlantPathology =                                                  "Plant Pathology",
  PoliticalScience =                                                "Political Science",
  Portuguese =                                                      "Portuguese",
  PowerEquipment =                                                  "Power Equipment",
  ProfessionalGolfManagement =                                      "Professional Golf Management",
  ProfessionalGolfManagementOnePlusThree =                          "Professional Golf Management 1+3",
  Psychology =                                                      "Psychology",
  PublicHealth =                                                    "Public Health",
  PublicManagementLeadershipAndPolicy =                             "Public Management, Leadership, and Policy",
  PublicPolicyAnalysis =                                            "Public Policy Analysis",
  RadiologicSciencesAndTherapy =                                    "Radiologic Sciences and Therapy",
  RealEstateAndUrbanAnalysis =                                      "Real Estate and Urban Analysis",
  ReligiousStudies =                                                "Religious Studies",
  RespiratoryTherapy =                                              "Respiratory Therapy",
  RomanceStudies =                                                  "Romance Studies",
  Russian =                                                         "Russian",
  SocialSciencesAirTransportation =                                 "Social Sciences Air Transportation",
  SocialWork =                                                      "Social Work",
  Sociology =                                                       "Sociology",
  Spanish =                                                         "Spanish",
  SpeechAndHearingScience =                                         "Speech and Hearing Science",
  SportIndustry =                                                   "Sport Industry",
  Statistics =                                                      "Statistics",
  SustainableAgriculture =                                          "Sustainable Agriculture",
  SustainablePlantSystems =                                         "Sustainable Plant Systems",
  Theatre =                                                         "Theatre",
  TurfgrassManagement =                                             "Turfgrass Management",
  UniversityExplorationArtsInnovationAndCreativityExploration =     "University Exploration - Arts Innovation and Creativity Exploration",
  UniversityExplorationBehaviorCultureAndContextExploration =       "University Exploration - Behavior, Culture, and Context Exploration",
  UniversityExplorationEducationAndPublicServiceExploration =       "University Exploration - Education and Public Service Exploration",
  UniversityExplorationHealthAndHumanServicesExploration =          "University Exploration - Health and Human Services Exploration",
  UniversityExplorationManagementAndIndustryExploration =           "University Exploration - Management and Industry Exploration",
  UniversityExplorationScienceTechnologyAndEnvironmentExploration = "University Exploration - Science, Technology, and Environment Exploration",
  UniversityExplorationUndecidedExploring =                         "University Exploration - Undecided/Exploring",
  VisionScience =                                                   "Vision Science",
  VisualCommunicationDesign =                                       "Visual Communication Design",
  WeldingEngineering =                                              "Welding Engineering",
  WomensGenderAndSexualityStudies =                                 "Women's, Gender, and Sexuality Studies",
  WorldLiteratures =                                                "World Literatures",
  WorldPolitics =                                                   "World Politics",
  Zoology =                                                         "Zoology",
}
// Undergraduate major (native) enums as Zod enums.
export const UndergradMajors = z.nativeEnum(NativeUndergradMajors);
export type UndergradMajors = z.infer<typeof UndergradMajors>;

// Undergraduate pre-professional route enums.
export enum NativeUndergradPreProfRoutes {
  PreDentistry =          "Pre-Dentistry",
  PreLaw =                "Pre-Law",
  PreMedicine =           "Pre-Medicine",
  PreOptometry =          "Pre-Optometry",
  PrePharmacy =           "Pre-Pharmacy",
  PreVeterinaryMedicine = "Pre-Veterinary Medicine",
}
// Undergraduate pre-professional route (native) enums as Zod enums.
export const UndergradPreProfRoutes = z.nativeEnum(NativeUndergradPreProfRoutes);
export type UndergradPreProfRoutes = z.infer<typeof UndergradPreProfRoutes>;
