// ./src/models/v1/osuStringLiterals.ts
//
// String literals arrays of OSU's undergrad year, major and pre-prof options.

// Undergraduate year options string literals, for creating zod enums.
export const UndergradYearsArray = [
  "High School",
  "Freshman (1st Year)",
  "Sophomore (2nd Year)",
  "Junior (3rd Year)",
  "Senior (4th Year)",
  "SuperSenior (5+ Years)"
] as const;

// Undergraduate major options string literals for creating zod enums.
// NOTE!
// Data manually collected on 06/28/24
// from `https://undergrad.osu.edu/majors-and-academics/majors`.
export const UndergradMajorsArray = [
  "Accounting",
  "Actuarial science",
  "Aerospace Engineering",
  "African American and African Studies",
  "Agribusiness",
  "Agricultural and Applied Economics",
  "Agricultural Communication",
  "Agricultural Systems Management",
  "Agriculture, Exploring",
  "Agriscience Education",
  "Agronomy",
  "Ancient History and Classics",
  "Animal Sciences",
  "Anthropological Sciences",
  "Anthropology",
  "Arabic",
  "Architecture",
  "Art",
  "Art Education",
  "Arts and Sciences, Undecided",
  "Arts Management",
  "Astronomy and Astrophysics",
  "Atmospheric Sciences",
  "Aviation",
  "Aviation Management",
  "Biochemical Sciences",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Science",
  "Business Administration, Undecided",
  "Business Management",
  "Chemical Engineering",
  "Chemistry",
  "Child and Youth Studies",
  "Chinese",
  "City and Regional Planning",
  "Civil Engineering",
  "Classics",
  "Communication",
  "Community Leadership",
  "Comparative Studies",
  "Computer and Information Science",
  "Computer Science and Engineering",
  "Construction Management",
  "Construction Systems Management",
  "Consumer and Family Financial Services",
  "Criminology and Criminal Justice Studies",
  "Crop Management and Soil Conservation",
  "Culinary Science",
  "Dairy Cattle Production and Management",
  "Dance",
  "Data Analytics",
  "Dental Hygiene",
  "Dental Hygiene (Baccaulaureate Completion Program)",
  "Earth Sciences",
  "Economics",
  "Economic - Business",
  "Education - Integrated Language Arts/English Education",
  "Education - Middle Childhood Education",
  "Education - Primary Education",
  "Education - Science and Mathematics Education",
  "Education - Special Education",
  "Education - Teaching English to Speakers of Other Languages",
  "Education - Technical Education and Training",
  "Education - World Language Education",
  "Electrical and Computer Engineering",
  "Engineering Physics",
  "Engineering Technology",
  "English",
  "Entomology",
  "Environment and Natural Resources",
  "Environment and Natural Resources, Undecided",
  "Environment, Economy, Development, and Sustainability",
  "Environmental Engineering",
  "Environmental Policy and Decision Making",
  "Environmental Science",
  "Evolution and Ecology",
  "Exercise Science Education",
  "Fashion and Retail Studies",
  "Film Studies",
  "Finance",
  "Food Business Management",
  "Food Science and Technology",
  "Food, Agricultural, and Biological Engineering",
  "Forensic Anthropology",
  "Forestry, Fisheries, and Wildlife",
  "French",
  "French and Francophone Studies",
  "Geographic Information Science",
  "Geography",
  "German",
  "Greenhouse and Nursery Management",
  "Health and Rehabilitation Sciences, Undecided",
  "Health and Wellness",
  "Health Information Management and Systems",
  "Health Promotion, Nutrition, and Exercise Science",
  "Health Sciences",
  "Hebrew and Jewish Studies",
  "History",
  "History of Art",
  "Horse Production and Management",
  "Horticulture Science",
  "Hospitality Management",
  "Human Development and Family Science",
  "Human Nutrition",
  "Human Resources",
  "Hydraulic Power and Motion Control",
  "Hydraulic Service and Repair",
  "Industrial and Systems Engineering",
  "Industrial Design",
  "Information Systems",
  "Insurance",
  "Integrated Major in Mathematics and English",
  "Interior Design",
  "International Business",
  "International Studies",
  "Islamic Studies",
  "Italian",
  "Italian Studies",
  "Japanese",
  "Journalism",
  "Korean",
  "Landscape Architecture",
  "Landscape Horticulture",
  "Linguistics",
  "Livestock Production and Management",
  "Logistics Management",
  "Marketing",
  "Materials Science and Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Anthropology",
  "Medical Laboratory Science",
  "Medieval and Renaissance Studies",
  "Microbiology",
  "Modern Greek",
  "Molecular Genetics",
  "Moving-Image Production",
  "Music",
  "Music - Composition",
  "Music - Education",
  "Music - Jazz Studies",
  "Music - Musicology",
  "Music - Performance (Orchestral Instruments)",
  "Music - Performance (Piano)",
  "Music - Performance (Voice)",
  "Music - Theory",
  "Natural Resources Management",
  "Neuroscience",
  "Nursing",
  "Nursing (RN to BSN)",
  "Occupational Therapy",
  "Operations Management",
  "Pharmaceutical Sciences",
  "Philosophy",
  "Philosophy, Politics, and Economics",
  "Physical Therapy",
  "Physics",
  "Plant Pathology",
  "Political Science",
  "Portuguese",
  "Power Equipment",
  "Professional Golf Management",
  "Professional Golf Management 1+3",
  "Psychology",
  "Public Health",
  "Public Management, Leadership, and Policy",
  "Public Policy Analysis",
  "Radiologic Sciences and Therapy",
  "Real Estate and Urban Analysis",
  "Religious Studies",
  "Respiratory Therapy",
  "Romance Studies",
  "Russian",
  "Social Sciences Air Transportation",
  "Social Work",
  "Sociology",
  "Spanish",
  "Speech and Hearing Science",
  "Sport Industry",
  "Statistics",
  "Sustainable Agriculture",
  "Sustainable Plant Systems",
  "Theatre",
  "Turfgrass Management",
  "University Exploration - Arts Innovation and Creativity Exploration",
  "University Exploration - Behavior, Culture, and Context Exploration",
  "University Exploration - Education and Public Service Exploration",
  "University Exploration - Health and Human Services Exploration",
  "University Exploration - Management and Industry Exploration",
  "University Exploration - Science, Technology, and Environment Exploration",
  "University Exploration - Undecided/Exploring",
  "Vision Science",
  "Visual Communication Design",
  "Welding Engineering",
  "Women's, Gender, and Sexuality Studies",
  "World Literatures",
  "World Politics",
  "Zoology"
] as const;


// Undergraduate pre-professional route options as string literals,
// for creating zod enums for schema validation.
export const UndergradPreProfRoutesArray = [
  "Pre-Dentistry",
  "Pre-Law",
  "Pre-Medicine",
  "Pre-Optometry",
  "Pre-Pharmacy",
  "Pre-Veterinary Medicine"
] as const;
