// ./src/models/top200WorldLanguagesTuple.ts
//
// String literals tuple of top 200 most used world languages.
// Source: https://internetlanguages.org/media/pdf/PS_Figure_3-full_language_matrix.pdf
// Surveyed: 2020
// Accessed: 07/12/24

// IMPORTANT!!
// Using TypeScript Tuple type to create a fixed-length array of string literals.
// Do NOT type the array as `string[]` or `Array<string>`, as this will allow
// any number of elements of any type to be added to the array.

// Top 200 language options string literals, for creating zod enums.
export const Top200WorldLanguagesTuple = [
  "English - English",
  "Chinese, Mandarin - 普通话",
  "Hindi - हिन्दी",
  "Spanish - Español",
  "French - Français",
  "Arabic, Standard - العربية الفصحى",
  "Bengali - বাংলা",
  "Russian - Русский",
  "Portuguese - Português",
  "Indonesian - Bahasa Indonesia",
  "Urdu - اُردُو",
  "German, Standard - Deutsch",
  "Japanese - 日本語",
  "Swahili - Kiswahili",
  "Marathi - मराठी",
  "Telugu - తెలుగు",
  "Punjabi, Western - پنجابی",
  "Chinese, Wu - 吴语",
  "Tamil - தமிழ்",
  "Turkish - Türkçe",
  "Korean - 한국어",
  "Vietnamese - Tiếng Việt",
  "Chinese, Yue - 粤语",
  "Javanese - ꦧꦱꦗꦮ",
  "Italian - Italiano",
  "Arabic, Egyptian Spoken - العربية المصرية",
  "Hausa - هَوُسَ",
  "Thai - ไทย",
  "Gujarati - ગુજરાતી",
  "Kannada - ಕನ್ನಡ",
  "Persian, Iranian - فارسی",
  "Bhojpuri - भोजपुरी",
  "Chinese, Min Nan - 闽南语",
  "Chinese, Hakka - 客家话",
  "Chinese, Jinyu - 晋语",
  "Filipino - Filipino",
  "Burmese - မြန်မာစာ",
  "Polish - Polski",
  "Yoruba - Yorùbá",
  "Odia - ଓଡ଼ିଆ",
  "Malayalam - മലയാളം",
  "Chinese, Xiang - 湘语",
  "Maithili - मैथिली",
  "Ukrainian - Українська",
  "Arabic, Moroccan Spoken - الدارجة المغربية",
  "Punjabi, Eastern - ਪੰਜਾਬੀ",
  "Sunda - Basa Sunda",
  "Arabic, Algerian Spoken - الدارجة الجزائرية",
  "Arabic, Sudanese Spoken - اللهجة السودانية",
  "Pidgin, Nigerian - Naijá",
  "Zulu - isiZulu",
  "Igbo - Asụsụ Igbo",
  "Amharic - አማርኛ",
  "Uzbek, Northern - Ўзбек",
  "Sindhi - سنڌي",
  "Arabic, North Levantine Spoken - اللهجة الشامية",
  "Nepali - नेपाली",
  "Romanian - Română",
  "Tagalog - Tagalog",
  "Dutch - Nederlands",
  "Arabic, Sa idi Spoken - الصعيدية",
  "Chinese, Gan - 赣语",
  "Pashto, Northern - پښتو",
  "Magahi - मगही",
  "Saraiki - سرائیکی",
  "Xhosa - isiXhosa",
  "Malay - Bahasa Melayu",
  "Khmer - ភាសាខ្មែរ",
  "Afrikaans - Afrikaans",
  "Sinhala - සිංහල",
  "Somali - Soomaali",
  "Chhattisgarhi - छत्तीसगढ़ी",
  "Cebuano - Cebuano",
  "Arabic, Mesopotamian Spoken - لهجة بغدادية",
  "Assamese - অসমীয়া",
  "Thai, Northeastern - ภาษาอีสาน",
  "Kurdish, Northern - Kurdî",
  "Arabic, Hijazi Spoken - اللهجة الحجازية",
  "Fulfulde, Nigerian - Pulaar",
  "Bavarian - Boarisch",
  "Bamanankan - Bamanankan",
  "Azerbaijani, South - Azərbaycan",
  "Sotho, Northern - Sesotho sa Leboa",
  "Setswana - Setswana",
  "Sotho, Southern - Sesotho",
  "Czech - Čeština",
  "Greek - Ελληνικά",
  "Chittagonian - চাটগাঁইয়া",
  "Kazakh - Қазақ",
  "Swedish - Svenska",
  "Deccan - دکنی",
  "Hungarian - Magyar",
  "Jula - Dioula",
  "Sadri - सादरी",
  "Kinyarwanda - Ikinyarwanda",
  "Pidgin, Cameroon - Pidgin",
  "Sylheti - সিলেটি",
  "Arabic, South Levantine Spoken - اللهجة الشامية الجنوبية",
  "Arabic, Tunisian Spoken - اللهجة التونسية",
  "Arabic, Sanaani Spoken - اللهجة الصنعانية",
  "Swahili, Congo - Kiswahili",
  "Chinese, Min Bei - 闽北语",
  "Pashto, Southern - پښتو",
  "Rangpuri - ৰংপুৰীয়া",
  "Rundi - Ikirundi",
  "Arabic, Ta izzi-Adeni Spoken - اللهجة التعزية-العَدَنية",
  "Uyghur - ئۇيغۇرچە",
  "Chinese, Min Dong - 閩東語",
  "Koongo - Kikongo",
  "Ibibio - Ibibio",
  "Haryanvi - हरियाणवी",
  "Arabic, Gulf Spoken - اللهجة الخليجية",
  "Chichewa - Chichewa",
  "Kanauji - कन्नौजी",
  "Hebrew - עִבְרִית",
  "Akan - Akan",
  "Azerbaijani, North - Azərbaycanca",
  "Catalan - Català",
  "Shona - chiShona",
  "Dari - دری",
  "Oromo, West Central - Afaan Oromoo",
  "Tsonga - Xitsonga",
  "Hassaniyya - حسانية",
  "Serbian - Српски",
  "Arabic, North Mesopotamian Spoken - لهجة الموصلية",
  "Bulgarian - Български",
  "Sukuma - Kisukuma",
  "Tajik - Тоҷикӣ",
  "Marwari - मारवाड़ी",
  "Venetian - Vèneto",
  "Kanuri, Yerwa - Kanuri",
  "Mòoré - Mòoré",
  "Madura - Basa Madura",
  "Tigrigna - ትግርኛ",
  "Santhali - सन्थाली",
  "Haitian Creole - Kreyòl Ayisyen",
  "Malagasy, Plateau - Malagasy",
  "Slovak - Slovenčina",
  "Tachelhit - Tacelḥit",
  "Luba-Kasai - Tshiluba",
  "Varhadi-Nagpuri - वर्‍हाडी",
  "Kashmiri - كشميري",
  "Turkmen - Türkmen",
  "Croatian - Hrvatski",
  "Gikuyu - Gĩkũyũ",
  "Ganda - Luganda",
  "Pashto, Central - پښتو",
  "Ilocano - Ilokano",
  "Finnish - Suomi",
  "Hiligaynon - Hiligaynon",
  "Guaraní, Paraguayan - Avañe'ẽ",
  "Thai, Northern - คำเมือง",
  "Umbundu - Umbundu",
  "Krio - Krio",
  "German, Swiss - Schwiizerdütsch",
  "Napoletano-Calabrese - Napoletano-Calabrese",
  "Danish - Dansk",
  "Bundeli - बुन्देली",
  "Kabyle - Taqbaylit",
  "Malvi - मालवी",
  "Pular - 𞤆𞤵𞤤𞤢𞤪",
  "Norwegian - Norsk",
  "Wolof - Wolof",
  "Sango - Sängö",
  "Lambadi - लमाणी",
  "Tatar - Татарча",
  "Sanskrit - संस्कृतम्",
  "Ghanaian Pidgin English - Ghanaian Pidgin",
  "Betawi - Betawi",
  "Kituba - Kituba",
  "Arabic, Libyan Spoken - اللهجة الليبية",
  "Kyrgyz - Кыргызча",
  "Swati - siSwati",
  "Tamazight, Central Atlas - Tamazight",
  "Sicilian - Sicilianu",
  "Éwé - Èʋe",
  "Baoulé - Baoulé",
  "Chinese, Huizhou - 徽州话",
  "Arabic, Hadrami Spoken - اللهجة الحضرمية",
  "Oromo, Eastern - Afaan Oromoo",
  "Kurdish, Central - کوردی",
  "Lao - ພາສາລາວ",
  "Thai, Southern - ภาษาไทยใต้",
  "Kamba - Kikamba",
  "Pulaar - Pulaar",
  "Awadhi - अवधी",
  "Tarifit - Tarifit",
  "Uzbek, Southern - Ўзбек",
  "Minangkabau - Baso Minangkabau",
  "Dholuo - Dholuo",
  "Mewari - मेवाड़ी",
  "Arabic, Najdi Spoken - اللهجة النجدية",
  "Tok Pisin - Tok Pisin",
  "Bemba - Chibemba",
  "Indian Sign Language - भारतीय सांकेतिक भाषा",
  "Balochi, Southern - بلوچی",
  "Bugis - Basa Ugi",
  "Tiv - Tiv",
  "Oromo, Borana-Arsi-Guji - Afaan Oromoo",
  "Lombard - Lumbaart"
] as const;
